### ISSUE TITLE
Arpitan is lost (like IRL?)

### ISSUE THREAD

**Issue by frostedoyster** [Luthaf/vesin#8]
Arpitan isn't showing in the readme or the docs, although we have a flag image for it. I suppose this wasn't meant to happen (?)

**Comment by Luthaf** [comment]
I unfortunately had to remove one of the languages since they where not fitting in the page width for the docs, which created ugly scrolling bars. Arpitan was the one to go since the word is the same as Occitan. I realized this after adding the flags, hence why there is a flag around =)

We could try to add it back in the README, but even there horizontal space is scarce unfortunately …

**Comment by frostedoyster** [comment]
Ahhh I suspected that. Maybe the two English varieties can be compressed in a single column, as in neighbo(u)r, neighbor/neighbour etc.
Anyway, I don't mind too much

**Comment by Luthaf** [comment]
Fixed in be51f91532c5ddc9573d73960e42bf752fd0b030!
